### ISSUE TITLE
Error when use with fresh jetstream v2

### ISSUE THREAD

**Issue by vanthao03596** [livewire/turbolinks#13]
I try this with turbo then i got error "Livewire: It looks like Livewire's @livewireScripts JavaScript assets have already been loaded. Make sure you aren't loading them twice".

**Comment by pyyjac** [comment]
Works for me _out of the box_. Are you sure, that you have added the cdn link **after** _@livewireScripts_ in the _app.blade.php_?

**Comment by vanthao03596** [comment]
Livewire fixed this, close now
