### ISSUE TITLE
Turbolinks Menu drawer not working

### ISSUE THREAD

**Issue by tahirafridi** [livewire/turbolinks#16]
![image](https://user-images.githubusercontent.com/4971486/105626077-7a2b0880-5e4f-11eb-8bb4-61c159875cfd.png)

Clicking these buttons in mobile browsers, it is not working. It was also not working in desktop browsers, but After fixing things from the community, its now working, but still it has issues with mobile browsers. When come to website first time, it working, when going another link/page then it stop working.

Here I've My website link for demo:  [Prize Bond](https://eprize.pk).

**Comment by pyyjac** [comment]
On iPhone iOS 14.4 it works, tested with Safari and Firefox. From Startpage and even after reading some sites. But your search function doesn't search anything. ;-)

**Comment by tahirafridi** [comment]
> On iPhone iOS 14.4 it works, tested with Safari and Firefox. From Startpage and even after reading some sites. But your search function doesn't search anything. ;-)

Thank you for checking it out, but I removed the turbolinks from my website as it was giving me issues with bootstrap modals and this menu thing, because I think the support is bit busy to reply for such issues. Hope they will consider it, as so many users around the internet complaining this type of issue with custom javascript or any other js frameworks.
