### ISSUE TITLE
Browser back button not working

### ISSUE THREAD

**Issue by RahulDey12** [livewire/turbolinks#2]
After clicking the back button on the browser URL is changing but the content is not updating.

**Comment by jameslkingsley** [comment]
Possibly because of this: https://github.com/livewire/livewire/commit/f7561d014b91c28e6e4774b9491c5dec00c7a711#diff-fe0ca20d2d8f013789d5ac617503cdddL123

**Comment by YannickYayo** [comment]
I have the same issue, pressing the back button update the URL, but the page's body doesn't change :(

**Comment by calebporzio** [comment]
Can you confirm that you are on the latest version of this package AND livewire?

**Comment by RahulDey12** [comment]
@calebporzio yes livewire is the latest one and for this package, I am using CDN so hopefully, it is also the latest.

**Comment by RahulDey12** [comment]
> Possibly because of this: [livewire/livewire@f7561d0#diff-fe0ca20d2d8f013789d5ac617503cdddL123](https://github.com/livewire/livewire/commit/f7561d014b91c28e6e4774b9491c5dec00c7a711#diff-fe0ca20d2d8f013789d5ac617503cdddL123)

I think It can be

**Comment by calebporzio** [comment]
Yes, but that code was added back into the most recent version of Livewire. Please post your exact versions of both this adapter and your Livewire install for sanity checking. Thanks!

**Comment by RahulDey12** [comment]
Livewire version: 2.1.2
The adapter is the CDN link

By the way sorry for late reply

**Comment by RahulDey12** [comment]
Ok, 
 It is working now after updating to livewire v2.2.2

Thanks @calebporzio 🚀
