### ISSUE TITLE
Suggestion: Provide a bit of a roadmap / objectives in the readme?

### ISSUE THREAD

**Issue by kurucu** [livewire/turbolinks#4]
Caleb and team,

Thanks for your continuing awesome work!

Could you please look at providing an intro for this package, that helps usage by covering:

- Why turbolinks was removed from Livewire natively
- Does this package aim to close all gaps, or are issues/divergence foreseen?
- Any limitations in its application?

Having taken advantage of turbolinks in v1, and now having upgraded to v2, I think I won't be alone in wondering whether this package will remain aligned to livewire, or whether support  may alter over time - aka should I remove turbolinks from my livewire app?

**Comment by calebporzio** [comment]
That's a great suggestion. I'll add a note.

**Comment by kurucu** [comment]
Awesome, thanks Caleb.
