### ISSUE TITLE
how to add it in a laravel proejct

### ISSUE THREAD

**Issue by thatsenam** [livewire/turbolinks#5]
composer require "livewire/turbolinks" does not works

**Comment by rafael-franca** [comment]
You can only use Composer with PHP packages. This adapter is a JavaScript package. You can only add this line:
`<script src="https://cdn.jsdelivr.net/gh/livewire/turbolinks@v0.1.x/dist/livewire-turbolinks.js" data-turbolinks-eval="false"></script>` after your `@livewireScripts` or `<livewire:scripts>`.

You can compile into your `app.js` too. Run `npm add --save-dev livewire-turbolinks` in root of your project, and import into your app.js: `import 'livewire-turbolinks'`.

PS: You need to add your `app.js` into head element. Use the `defer` to optimize the load. `<script src="{{ mix('js/app.js') }}" defer></script>`
PS 2: Change the `app.js` with name of your js file.

**Comment by calebporzio** [comment]
Thanks @rafael-franca !
