### ISSUE TITLE
Which issues I am going to deal when using this adapter?

### ISSUE THREAD

**Issue by thewebartisan7** [livewire/turbolinks#7]
I would like to know which issue I am going to deal when using this adapter. About what is written in readme: "because of certain features that are difficult to **impossible** to make work perfectly with Turbolinks and all it's configurations".

Apart all issues well knowed with turbolinks, I would like to know specific with livewire.

Thanks

**Comment by calebporzio** [comment]
Yeah, there's actually nothing explicitly impossible at the moment. I'm going to change it.

What I'm referring to is anything dealing with modifying the historyState on Livewire's end. Which is namely: the `$queryString` property, and some future Turbolinks-esque features I'd like to implement.

Thanks
