### ISSUE TITLE
turbolinks doesn't work with livewire 2

### ISSUE THREAD

**Issue by sxshateri** [livewire/turbolinks#9]
Ok so as per docs for this to work you just have to add it after the livewire script and we will take care of the rest. so i did but nothing changed. the whole page is still loading on every click. so what am i doing wrong?

i have 2 livewire views. one "profile-info" and another one "profile-settings". there is a side menu which has links to these pages and i would like to remove the whole page load using turbolinks. but after adding the CDN to the app.blade.php file it's still the same old thing. do i have to do something else that the docs didn't say?

**Comment by AdvancedStyle** [comment]
Did you figure this out?
